In [2]:
import numpy as np
import torch

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')



In [3]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [4]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.6427, -0.8392, -0.8129],
        [-0.2888, -1.3780,  1.1553]], requires_grad=True)
tensor([2.1267, 0.3329], requires_grad=True)


In [5]:
def model(x):
    return x @ w.t() + b

In [6]:
# Generate predictions
preds = model(inputs)
print(preds)
# Compare with targets
print(targets)

tensor([[-135.9711,  -63.4013],
        [-182.2336,  -73.2771],
        [-213.3873, -142.4433],
        [-129.5922,  -45.6367],
        [-179.6847,  -71.0150]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [7]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [8]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(48648.8945, grad_fn=<DivBackward0>)


In [9]:
# Compute gradients
loss.backward()